### ISSUE TITLE
Prevalence filtering question

### ISSUE THREAD

**Issue by gavinmdouglas** [bsmith89/StrainFacts#12]
Hey Byron,

I hope all is well with you! Just a quick question -- in your `filter_data.ipynb` notebook you pre-processed the example data so that polymorphic sites found in < 5% of samples were excluded. Have you explored how robust StrainFacts is when this filtering step isn't performed? I'm actually interested in strains that might be sample-specific (and as long as they are at sufficient depth in that sample I'm not too worried about false positives).

Thanks!

Gavin

**Comment by bsmith89** [comment]
Thanks for reaching out!

I have not explored that deeply, no, so can't comment about robustness directly, but I do have some intuition and related thoughts worth mentioning.

- The filtering is intended, in part, to reduce the impact of sequencing errors. If you are confident that a variant is real and informative, it should theoretically improve the accuracy to include it.
- Including lots of mostly constant (un-informative) positions and/or positions that are merely "noise" may interact with the regularization parameters. Hyper-parameter tuning may be valuable if the defaults aren't working well.
- The processor and memory requirements scale mostly linearly with the number of positions. Eventually when you max something out you'll have to subsample positions, at which point including low-frequency SNPs means you'll lose information from high-frequency SNPs that could have been important for accurate inferences.
- StrainFacts generally performs poorly when you have one or more of: low sequencing depth, high strain-heterogeneity, or very few samples with a given strain. As a consequence, I don't think it's the right tool for exploring in situ evolution, since novel variation is basically going to have all three of those problems... 😅 So depending on what you mean by "strains that might be sample-specific", do keep that in mind.

I hope these thoughts are useful (and I hope StrainFacts is useful, too)!

**Comment by gavinmdouglas** [comment]
Thanks Byron, that's very helpful! I'm going to see how things change with and without prevalence cut-offs for the data I'm using... I'll keep your advice in mind.


Cheers,

Gavin
